// This file is generated by GoAdmin CLI adm.
package main

import "github.com/GoAdminGroup/go-admin/plugins/admin/modules/table"

// The key of Generators is the prefix of table info url.
// The corresponding value is the Form and Table data.
//
// http://{{config.Domain}}:{{Port}}/{{config.Prefix}}/info/{{key}}
//
// example:
//
// "call_trace" => http://localhost:9033/admin/info/call_trace
// "call_trace_config" => http://localhost:9033/admin/info/call_trace_config
//
// example end
var Generators = map[string]table.Generator{

	"call_trace":        GetCallTraceTable,
	"call_trace_config": GetCallTraceConfigTable,

	// generators end
}
