version: '3'
services:
  db:
    image: durd07/subscriber-tracing-db:latest
    container_name: subscriber-tracing-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=subscriber_tracing
    expose:
      - 3306

  service:
    image: durd07/subscriber-tracing:latest
    container_name: subscriber-tracing
    environment:
      - MYSQL_HOST=db
    restart: always
    ports:
      - "9033:9033"
      - "9034:9034"
    links:
      - db:db

networks:
  default:
    driver:
      bridge
